# Site settings
author: Elliot Blanchard
title: Design to Dev
header-img: img/home-bg.png
email: public@elliotblanchard.com
copyright_name: Elliot Blanchard
description: > # this means to ignore newlines until "baseurl:"
  Exploring Code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  elliotblanchard

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
